import { AUTH_CONFIG_KEYS } from '@constant/authentication/auth';

export default () => ({
  [AUTH_CONFIG_KEYS.JWT_SECRET]: process.env.JWT_SECRET,
  [AUTH_CONFIG_KEYS.ACCESS_TOKEN_DURATION]: '20d',
  [AUTH_CONFIG_KEYS.REFRESH_TOKEN_DURATION]: '20d',
  [AUTH_CONFIG_KEYS.REFRESH_TOKEN_OFFLINE_DURATION]: '60 days',
  [AUTH_CONFIG_KEYS.VERIFICATION_TOKEN_DURATION]: 10 * 60,
});
