export enum SIP_SETTINGS {
  USE_WEB_RTC = 'USE_WEB_RTC',
  USE_OUTSOURCED_SOFT_PHONE = 'USE_OUTSOURCED_SOFT_PHONE',
}

export enum TWO_FACTOR_AUTHENTICATION_TYPE {
  DISABLED = 'DISABLED',
}

export enum ACTIVE_STATE {
  ALL = 'ALL',
  ACTIVE = 'ACTIVE',
  DE_ACTIVE = 'DE_ACTIVE',
}

export enum MISC_TYPE {
  DESK = 'DESK',
  SKILL_GROUP = 'SKILL_GROUP',
  ROLE = 'ROLE',
}
