export enum AUTH_CONFIG_KEYS {
  JWT_SECRET = 'JWT_SECRET',
  ACCESS_TOKEN_DURATION = 'ACCESS_TOKEN_DURATION',
  REFRESH_TOKEN_DURATION = 'REFRESH_TOKEN_DURATION',
  REFRESH_TOKEN_OFFLINE_DURATION = 'REFRESH_TOKEN_OFFLINE_DURATION',
  VERIFICATION_TOKEN_DURATION = 'VERIFICATION_TOKEN_DURATION',
}
